### ISSUE TITLE
Mongo version issue

### ISSUE THREAD

**Issue by inspire12** [kijepark/adserver-tutorial#20]
Hi!, I try to build this project in my local environment.

but i don't install mongo db but docker.

so i try to install mongo via docker latest. 
```bash 
docker run -d --name mongo_ad
       -e MONGO_INITDB_ROOT_USERNAME=admin
       -e MONGO_INITDB_ROOT_PASSWORD=1q2w3e4r
       -e MONGODB_DATABASE=adserver
       -p 27017:27017
       mongo --auth
```
but when run project, it raise MongoError: command aggregate requires authentication

so I fork your project and add command in config.json 

```
{
  "database": {
... 
    "options": {
...
      "user": "admin",
      "pass": "1q2w3e4r",
      "auth": { "authSource": "admin" }
    }
  }
}
```

If you accept this issue, can I  pr this issue?
or would you inform mongo version?

**Comment by kijepark** [comment]
Just added version of database, Thanks for your issue
